FROM python:3.13-slim

WORKDIR /usr/local/app

COPY requirements_streamlit.txt ./

RUN pip install --no-cache-dir --prefer-binary -r requirements_streamlit.txt

COPY app.py ./
COPY feature_columns.pkl ./
COPY demo_csv ./demo_csv
COPY exoplanet_image.png ./
COPY auc_data.npz ./

EXPOSE 8501

# Create a non-root user for safer container execution.
RUN useradd --create-home app

USER app

CMD ["streamlit", "run", "app.py", \
     "--server.address=0.0.0.0", \
     "--server.port=8501"]